import Head from 'next/head'
import HeaderComponent from '../components/Homepage/header-component'
import stylesHp from '../styles/Homepage/Homepage.module.css';
import { getAllHomepage, getHomepageById } from "../lib/Homepage/homepage-lib";
import Homepage from "../types/Homepage/homepage-type";
import FooterComponent from '../components/Homepage/footer-component';
import { HOMEPAGE_ID } from '../lib/Common/constants';

import { getClothingById } from '../lib/Clothings/clothings-lib';
import Clothing from '../types/Clothings/clothings-type';
import RichText from '../components/Common/richText-component';

export async function getStaticProps({ preview = false }) {
  const allHomepage = await getAllHomepage(preview);
  const homepage = await getHomepageById(HOMEPAGE_ID);
  const clothing = await getClothingById('4RLCyRy530OnwpTnCUz59A');
  return {
    props: { allHomepage, homepage, clothing, preview },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, //in seconds
  }
}

type Props = {
  allHomepage: Homepage[];
  homepage: Homepage;
  clothing: Clothing;
}

const Homepage = ({ allHomepage, homepage, clothing }: Props) => {
  //const homepage = allHomepage[0];

  return (
    <div className={stylesHp.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={stylesHp.main}>
        <HeaderComponent
          allHeaders={homepage.header}
        />
        <div className={stylesHp.boxedContainer}>
          <h1 className={stylesHp.title}>
            {/* {clothing.productName} */}
          </h1>
          <p className={stylesHp.SectionDescription}>{clothing.description}</p>
        </div>
        <FooterComponent
          allFooters={homepage.footer}
        />
      </main>


    </div>
  )
}
export default Homepage;
